meta_product_name: "QuietRent"
meta_title: "QuietRent - Réduire le risque locatif"
meta_description: "Solution innovante de reduction du risque locatif"
meta_image: "logo-quietrent-meta.png"                           # Une image dans votre dossier app/assets/images/
twitter_account: "@QuietRent"              # indispensable pour les Twitter Cards
